#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, displays "Hi" after
i=0
while [ "$i" -lt 10 ]; do
    i=$((i + 1))
    echo "Best School"
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    fi
done
