#!/usr/bin/env bash
# This script loops from 1 to 10 and displays bad luck for 4th, good luck for 8th, Best School for others
i=0
while [ "$i" -lt 10 ]; do
    i=$((i + 1))
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done
